options:
  env:
steps:
  - name: node:12-alpine
    entrypoint: npm
    args: ['install', 'firebase-tools']
  - name: node:12-alpine
    entrypoint: npm
    args: ['install']
  - name: node:12-alpine
    entrypoint: npm
    args: ['run', 'build']
    env:
      - 'GA_TAG_ID=$_GA_TAG_ID'
  - name: 'node:12-alpine'
    entrypoint: './node_modules/.bin/firebase'
    args: ['deploy', '--project', '$_ENVIRONMENT', '--token', '$_TOKEN']
